
services:
  tailscale-hap:
    image: tailscale/tailscale:latest
    hostname: tailscale-hap
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-hap/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  haproxy:
    image: haproxy:latest
    container_name: tailscale-haproxy
    environment:
      - DEFAULT_BACKEND=${DEFAULT_BACKEND:-localhost:3000}
    env_file:
      - ./.env
    ports:
      - ${HA_PROXY_PORT:-8080}:8080
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped
    depends_on:
      - tailscale-hap
